<footer class="bg-dark text-light py-5 mt-5">
  <div class="container text-center">
    <h4 class="fw-bold">Sabor Caseiro</h4>
    <p class="mb-3">
      Bolos artesanais feitos com carinho, ingredientes selecionados e aquele
      gostinho de casa que você merece.
    </p>
    <p class="mb-1">📍 Endereço: Rua Franz Kaizer, 1124 – Jardim Copacabana</p>
    <p class="mb-3">📞 Telefone: (44) 98411-2718</p>

    

    <small class="text-secondary">
      © <?= date('Y') ?> Sabor Caseiro — Todos os direitos reservados.
    </small>
  </div>
</footer>

<style>
    footer a {
  font-size: 1.2rem;
  transition: color 0.3s;
}
footer a:hover {
  color: #f8d7da; /* muda cor no hover */
}

</style>