
<?php $basePath = '/saborCaseiro_MVC/public'; ?>


<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="home">
        <img src="/img/logo.png" style="width: 100px; " alt="Sabor Caseiro">
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
       
        <li class="nav-item">
          <a class="nav-link" href="<?= $basePath ?>/home">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<?= $basePath ?>/quem-somos">Quem Somos</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<?= $basePath ?>/produtos">Produtos</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<?= $basePath ?>/contato">Contato</a>
        </li>

</nav>  



